import { AdsResponse, AdsProp, getAds, IAdsResponse } from "./adsApi";

import {
  ArticleResponse,
  getNewsEverything,
  getNewsTopHeadlines,
  IArticle,
  IMoreInfoPageProps,
  INewsEverythingRequest,
  INewsResponse,
  INewsTopHeadlinesRequest,
  NewsEverythingRequest,
  NewsProps,
  NewsResponse,
  NewsTopHeadlinesRequest,
} from "./newsApi";

import {
  Coords,
  Current,
  GeolocationPositionError,
  GeolocationPositionSuccess,
  getWeather,
  IWeatherRequest,
  IWeatherResponse,
  Location,
  Request,
  WeatherProp,
  WeatherRequest,
  WeatherResponse,
} from "./weatherApi";

export {
  AdsResponse,
  // AdsProp,
  ArticleResponse,
  // Coords,
  // Current,
  // GeolocationPositionError,
  // GeolocationPositionSuccess,
  getAds,
  getNewsEverything,
  getNewsTopHeadlines,
  getWeather,
  // IAdsResponse,
  // IArticle,
  // IMoreInfoPageProps,
  // INewsEverythingRequest,
  // INewsResponse,
  // INewsTopHeadlinesRequest,
  // IWeatherRequest,
  // IWeatherResponse,
  // Location,
  NewsEverythingRequest,
  // NewsProps,
  NewsResponse,
  NewsTopHeadlinesRequest,
  // Request,
  // WeatherProp,
  WeatherRequest,
  WeatherResponse,
};

export type {
  AdsProp,
  Coords,
  Current,
  GeolocationPositionError,
  GeolocationPositionSuccess,
  IAdsResponse,
  IArticle,
  IMoreInfoPageProps,
  INewsEverythingRequest,
  INewsResponse,
  INewsTopHeadlinesRequest,
  IWeatherRequest,
  IWeatherResponse,
  Location,
  NewsProps,
  Request,
  WeatherProp,
}
